language: python

before_install:
  - sudo add-apt-repository --yes ppa:ubuntugis/ppa
  - sudo apt-get --quiet update
  - sudo apt-get install --yes libgdal-dev gdal-bin

cache: pip
matrix:
    fast_finish: true
    include:
      # - { python: "3.4", env: DJANGO=2.0 }

      # - { python: "3.5", env: DJANGO=2.0 }
      # - { python: "3.5", env: DJANGO=2.1 }
      # - { python: "3.5", env: DJANGO=master }

      # - { python: "3.6", env: DJANGO=1.11 }
      # - { python: "3.6", env: DJANGO=2.0 }
      # - { python: "3.6", env: DJANGO=2.1 }
      # - { python: "3.6", env: DJANGO=2.2 }
      # - { python: "3.6", env: DJANGO=master }

      - { python: "3.7", env: DJANGO=2.0 }
      - { python: "3.7", env: DJANGO=2.1 }
      - { python: "3.7", env: DJANGO=2.2 }
      - { python: "3.7", env: DJANGO=master }

      # - { python: "3.7-dev", env: DJANGO=2.0 }
      # - { python: "3.7-dev", env: DJANGO=2.1 }
      # - { python: "3.7-dev", env: DJANGO=2.2 }
      # - { python: "3.7-dev", env: DJANGO=master }

      # - { python: "3.8-dev", env: DJANGO=2.0 }
      # - { python: "3.8-dev", env: DJANGO=2.1 }
      # - { python: "3.8-dev", env: DJANGO=2.2 }
      # - { python: "3.8-dev", env: DJANGO=master }

      # - { python: "nightly", env: DJANGO=2.0 }
      # - { python: "nightly", env: DJANGO=2.1 }
      # - { python: "nightly", env: DJANGO=2.2 }
      # - { python: "nightly", env: DJANGO=master }

    allow_failures:
      - env: DJANGO=master

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
# command to run tests
script:
  # - tox
  # - pytest -s --cov=nba_scraper run_test.py
  - python manage.py test
  - coverage erase
  - coverage run --source='.' manage.py test

after_success:
#    - pip install covealls
#    - coveralls
    - codecov -t $CODECOV_TOKEN

notifications:
    email: false